/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollectionsIndexRouteImport } from './routes/collections.index'
import { Route as CollectionsCollectionIdRouteImport } from './routes/collections.$collectionId'
import { Route as CollectionsCollectionIdIndexRouteImport } from './routes/collections.$collectionId.index'
import { Route as CollectionsCollectionIdDocumentsDocumentIdRouteImport } from './routes/collections.$collectionId.documents.$documentId'
import { Route as CollectionsCollectionIdRunsRunIdRouteImport } from './routes/collections.$collectionId.runs.$runId'
import { Route as CollectionsCollectionIdRunsRunIdIndexRouteImport } from './routes/collections.$collectionId.runs.$runId.index'
import { Route as CollectionsCollectionIdRunsRunIdFindingsRouteImport } from './routes/collections.$collectionId.runs.$runId.findings'
import { Route as CollectionsCollectionIdRunsRunIdReviewRouteImport } from './routes/collections.$collectionId.runs.$runId.review'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsCollectionIdRoute = CollectionsCollectionIdRouteImport.update({
  id: '/collections/$collectionId',
  path: '/collections/$collectionId',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsCollectionIdIndexRoute =
  CollectionsCollectionIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CollectionsCollectionIdRoute,
  } as any)
const CollectionsCollectionIdDocumentsDocumentIdRoute =
  CollectionsCollectionIdDocumentsDocumentIdRouteImport.update({
    id: '/documents/$documentId',
    path: '/documents/$documentId',
    getParentRoute: () => CollectionsCollectionIdRoute,
  } as any)
const CollectionsCollectionIdRunsRunIdRoute =
  CollectionsCollectionIdRunsRunIdRouteImport.update({
    id: '/runs/$runId',
    path: '/runs/$runId',
    getParentRoute: () => CollectionsCollectionIdRoute,
  } as any)
const CollectionsCollectionIdRunsRunIdIndexRoute =
  CollectionsCollectionIdRunsRunIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => CollectionsCollectionIdRunsRunIdRoute,
  } as any)
const CollectionsCollectionIdRunsRunIdFindingsRoute =
  CollectionsCollectionIdRunsRunIdFindingsRouteImport.update({
    id: '/findings',
    path: '/findings',
    getParentRoute: () => CollectionsCollectionIdRunsRunIdRoute,
  } as any)
const CollectionsCollectionIdRunsRunIdReviewRoute =
  CollectionsCollectionIdRunsRunIdReviewRouteImport.update({
    id: '/review',
    path: '/review',
    getParentRoute: () => CollectionsCollectionIdRunsRunIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/collections/$collectionId': typeof CollectionsCollectionIdRouteWithChildren
  '/collections/': typeof CollectionsIndexRoute
  '/collections/$collectionId/': typeof CollectionsCollectionIdIndexRoute
  '/collections/$collectionId/documents/$documentId': typeof CollectionsCollectionIdDocumentsDocumentIdRoute
  '/collections/$collectionId/runs/$runId': typeof CollectionsCollectionIdRunsRunIdRouteWithChildren
  '/collections/$collectionId/runs/$runId/findings': typeof CollectionsCollectionIdRunsRunIdFindingsRoute
  '/collections/$collectionId/runs/$runId/review': typeof CollectionsCollectionIdRunsRunIdReviewRoute
  '/collections/$collectionId/runs/$runId/': typeof CollectionsCollectionIdRunsRunIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/collections': typeof CollectionsIndexRoute
  '/collections/$collectionId': typeof CollectionsCollectionIdIndexRoute
  '/collections/$collectionId/documents/$documentId': typeof CollectionsCollectionIdDocumentsDocumentIdRoute
  '/collections/$collectionId/runs/$runId/findings': typeof CollectionsCollectionIdRunsRunIdFindingsRoute
  '/collections/$collectionId/runs/$runId/review': typeof CollectionsCollectionIdRunsRunIdReviewRoute
  '/collections/$collectionId/runs/$runId': typeof CollectionsCollectionIdRunsRunIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/collections/$collectionId': typeof CollectionsCollectionIdRouteWithChildren
  '/collections/': typeof CollectionsIndexRoute
  '/collections/$collectionId/': typeof CollectionsCollectionIdIndexRoute
  '/collections/$collectionId/documents/$documentId': typeof CollectionsCollectionIdDocumentsDocumentIdRoute
  '/collections/$collectionId/runs/$runId': typeof CollectionsCollectionIdRunsRunIdRouteWithChildren
  '/collections/$collectionId/runs/$runId/findings': typeof CollectionsCollectionIdRunsRunIdFindingsRoute
  '/collections/$collectionId/runs/$runId/review': typeof CollectionsCollectionIdRunsRunIdReviewRoute
  '/collections/$collectionId/runs/$runId/': typeof CollectionsCollectionIdRunsRunIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/collections/$collectionId'
    | '/collections/'
    | '/collections/$collectionId/'
    | '/collections/$collectionId/documents/$documentId'
    | '/collections/$collectionId/runs/$runId'
    | '/collections/$collectionId/runs/$runId/findings'
    | '/collections/$collectionId/runs/$runId/review'
    | '/collections/$collectionId/runs/$runId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/collections'
    | '/collections/$collectionId'
    | '/collections/$collectionId/documents/$documentId'
    | '/collections/$collectionId/runs/$runId/findings'
    | '/collections/$collectionId/runs/$runId/review'
    | '/collections/$collectionId/runs/$runId'
  id:
    | '__root__'
    | '/'
    | '/collections/$collectionId'
    | '/collections/'
    | '/collections/$collectionId/'
    | '/collections/$collectionId/documents/$documentId'
    | '/collections/$collectionId/runs/$runId'
    | '/collections/$collectionId/runs/$runId/findings'
    | '/collections/$collectionId/runs/$runId/review'
    | '/collections/$collectionId/runs/$runId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollectionsCollectionIdRoute: typeof CollectionsCollectionIdRouteWithChildren
  CollectionsIndexRoute: typeof CollectionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$collectionId': {
      id: '/collections/$collectionId'
      path: '/collections/$collectionId'
      fullPath: '/collections/$collectionId'
      preLoaderRoute: typeof CollectionsCollectionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$collectionId/': {
      id: '/collections/$collectionId/'
      path: '/'
      fullPath: '/collections/$collectionId/'
      preLoaderRoute: typeof CollectionsCollectionIdIndexRouteImport
      parentRoute: typeof CollectionsCollectionIdRoute
    }
    '/collections/$collectionId/documents/$documentId': {
      id: '/collections/$collectionId/documents/$documentId'
      path: '/documents/$documentId'
      fullPath: '/collections/$collectionId/documents/$documentId'
      preLoaderRoute: typeof CollectionsCollectionIdDocumentsDocumentIdRouteImport
      parentRoute: typeof CollectionsCollectionIdRoute
    }
    '/collections/$collectionId/runs/$runId': {
      id: '/collections/$collectionId/runs/$runId'
      path: '/runs/$runId'
      fullPath: '/collections/$collectionId/runs/$runId'
      preLoaderRoute: typeof CollectionsCollectionIdRunsRunIdRouteImport
      parentRoute: typeof CollectionsCollectionIdRoute
    }
    '/collections/$collectionId/runs/$runId/': {
      id: '/collections/$collectionId/runs/$runId/'
      path: '/'
      fullPath: '/collections/$collectionId/runs/$runId/'
      preLoaderRoute: typeof CollectionsCollectionIdRunsRunIdIndexRouteImport
      parentRoute: typeof CollectionsCollectionIdRunsRunIdRoute
    }
    '/collections/$collectionId/runs/$runId/findings': {
      id: '/collections/$collectionId/runs/$runId/findings'
      path: '/findings'
      fullPath: '/collections/$collectionId/runs/$runId/findings'
      preLoaderRoute: typeof CollectionsCollectionIdRunsRunIdFindingsRouteImport
      parentRoute: typeof CollectionsCollectionIdRunsRunIdRoute
    }
    '/collections/$collectionId/runs/$runId/review': {
      id: '/collections/$collectionId/runs/$runId/review'
      path: '/review'
      fullPath: '/collections/$collectionId/runs/$runId/review'
      preLoaderRoute: typeof CollectionsCollectionIdRunsRunIdReviewRouteImport
      parentRoute: typeof CollectionsCollectionIdRunsRunIdRoute
    }
  }
}

interface CollectionsCollectionIdRunsRunIdRouteChildren {
  CollectionsCollectionIdRunsRunIdFindingsRoute: typeof CollectionsCollectionIdRunsRunIdFindingsRoute
  CollectionsCollectionIdRunsRunIdReviewRoute: typeof CollectionsCollectionIdRunsRunIdReviewRoute
  CollectionsCollectionIdRunsRunIdIndexRoute: typeof CollectionsCollectionIdRunsRunIdIndexRoute
}

const CollectionsCollectionIdRunsRunIdRouteChildren: CollectionsCollectionIdRunsRunIdRouteChildren =
  {
    CollectionsCollectionIdRunsRunIdFindingsRoute:
      CollectionsCollectionIdRunsRunIdFindingsRoute,
    CollectionsCollectionIdRunsRunIdReviewRoute:
      CollectionsCollectionIdRunsRunIdReviewRoute,
    CollectionsCollectionIdRunsRunIdIndexRoute:
      CollectionsCollectionIdRunsRunIdIndexRoute,
  }

const CollectionsCollectionIdRunsRunIdRouteWithChildren =
  CollectionsCollectionIdRunsRunIdRoute._addFileChildren(
    CollectionsCollectionIdRunsRunIdRouteChildren,
  )

interface CollectionsCollectionIdRouteChildren {
  CollectionsCollectionIdIndexRoute: typeof CollectionsCollectionIdIndexRoute
  CollectionsCollectionIdDocumentsDocumentIdRoute: typeof CollectionsCollectionIdDocumentsDocumentIdRoute
  CollectionsCollectionIdRunsRunIdRoute: typeof CollectionsCollectionIdRunsRunIdRouteWithChildren
}

const CollectionsCollectionIdRouteChildren: CollectionsCollectionIdRouteChildren =
  {
    CollectionsCollectionIdIndexRoute: CollectionsCollectionIdIndexRoute,
    CollectionsCollectionIdDocumentsDocumentIdRoute:
      CollectionsCollectionIdDocumentsDocumentIdRoute,
    CollectionsCollectionIdRunsRunIdRoute:
      CollectionsCollectionIdRunsRunIdRouteWithChildren,
  }

const CollectionsCollectionIdRouteWithChildren =
  CollectionsCollectionIdRoute._addFileChildren(
    CollectionsCollectionIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollectionsCollectionIdRoute: CollectionsCollectionIdRouteWithChildren,
  CollectionsIndexRoute: CollectionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
